editor/editor/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
    path('student/', include('student.urls')),
    path('teacher/', include('teacher.urls')),
    path('makeTest/', include('makeTest.urls')),
]

editor/teacher/urls.py
from django.urls import path
from . import views

app_name = 'teacher'

urlpatterns = [
    path('', views.index, name='teacher_dashboard'),
    path('add_test', views.add_test, name='create_test'),
    path('test/<int:test_id>/question/<int:q_id>', views.add_question, name='add_question'),
    path('test/<int:test_id>/new_question/', views.new_question, name='new_question'),
]

editor/teacher/models.py
from django.db import models
from django.utils import timezone
from datetime import timedelta

class Test(models.Model):
    # date_and_time = models.DateTimeField(default = one_hour_from_now, blank=False, null=True)
    subject = models.CharField(max_length=100)
    subject_Code = models.CharField(max_length=100)
    # time_Duration = models.IntegerField(default=2)
    total_Marks = models.IntegerField(default=100)
    exam_code = models.CharField(max_length=100, default='123AB', blank=False)
    def __str__(self):
        return self.exam_code
    
class PublishedTest(models.Model):
    subject = models.CharField(max_length=100)
    subject_Code = models.CharField(max_length=100)
    total_Marks = models.IntegerField(default=100)
    exam_code = models.CharField(max_length=100, default='123AB', blank=False)
    def __str__(self):
        return self.exam_code
    
class Question(models.Model):
    test = models.ForeignKey(Test, on_delete=models.CASCADE)
    question_text = models.TextField()
    desired_output = models.TextField()
    max_score = models.IntegerField()
    
    def __str__(self):
        return self.question

editor/teacher/forms.py
# forms.py
from django import forms
from .models import Test, Question

class Test_Form(forms.ModelForm):
    class Meta:
        model = Test
        fields = ['subject_Code', 'subject', 'total_Marks']
        widgets = {
            'subject_Code': forms.TextInput(attrs={'class': 'form-control'}),
            'subject': forms.TextInput(attrs={'class': 'form-control'}),
            'total_Marks': forms.NumberInput(attrs={'class': 'form-control'}),
        }

editor/teacher/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.http import HttpResponse
from django.contrib import messages
from .models import Test, Question
from .forms import Test_Form
def index(request):
    return render(request, 'teacher/add_test.html', )

# def add_test(request):
#     if request.method == 'POST':
#         form = Test_Form(request.POST)
#         if form.is_valid():
#             form.save()
#             exam_code = genExamCode()
#             test = Test.objects.latest('id')
#             test.examcode = exam_code
#             test_id = test.id
#             test.save()
#             messages.success(request, 'Test created successfully')
#             return redirect('teacher/add_question', test_id=test_id, ques_id=1)
#         else:
#             print(form.errors)
#     else:
#         form = Test_Form()
#     return render(request, 'teacher/add_test.html', {'form': form, 'success': False})

def add_test(request):
    if request.method == 'POST':
        form = Test_Form(request.POST)
        if form.is_valid():
            test = form.save()
            exam_code = genExamCode()
            test.exam_code = exam_code
            test.save()
            question = Question.objects.create(test=test, question_text="")
            return redirect('add_question', test_id=test.pk, q_id=question.pk)
        else:
            form = Test_Form()
        return render(request, 'teacher/add_test.html', {'form': form})

def add_question(request, test_id, q_id=None):
    test = get_object_or_404(Test, pk=test_id)
    if request.method == 'POST':
        question_text = request.POST.get('question_text')
        if question_text and q_id is not None:
            current_question = get_object_or_404(Question, pk=q_id)
            current_question.question_text = question_text
            current_question.save()
        return redirect('add_question', test_id=test.pk, q_id=q_id)
    else:
        if q_id is None:
            current_question = Question.objects.create(test=test, question_text="")
        else:
            current_question = get_object_or_404(Question, pk=q_id)
        all_questions = Question.objects.filter(test=test)
        return render(request, 'createtest/add_question.html', {'test': test, 'question': current_question, 'all_questions': all_questions})
    
def new_question(request, test_id):
    test = get_object_or_404(Test, pk=test_id)
    new_question = Question.objects.create(test=test, question_text="")
    return redirect('add_question', test_id=test.pk, q_id=new_question.pk)

def QuestionCreation(request):
    return render(request, 'teacher/QuestionCreationWindow.html')


def genExamCode():
    import random
    import string
    return ''.join(random.choices(string.ascii_uppercase + string.digits, k=6))

editor/teacher/templates/teacher/QuestionCreationWindow.html
<style>
    body {
    background-image: url("https://c4.wallpaperflare.com/wallpaper/285/172/9/sunset-8k-forest-4k-wallpaper-preview.jpg");
    background-size: cover;
    background-repeat: no-repeat;
    background-attachment: fixed;
    display: flex;
    justify-content: center; 
    align-items: center; 
    
}

.MainBox {
    background-color: rgba(255, 255, 255, 0.9); 
    width: 90%; 
    max-width: 1390px; 
    height: 936px; 
    border-radius: 20px; 
    display: flex;
    justify-content: center;
    align-items: center;
    position: relative;
    backdrop-filter: blur(300px); 
    display: flex;
}

.Runs {
    position: absolute;
    top: 50px;
    left: 10vh; 
    background-color: rgb(255, 255, 255);
    font-family: 'K2D', sans-serif;
    border-radius: 20px;
    width: 303px;
    height: 58px;
    text-align: center; 
    display: flex;
    justify-content: center;
    align-items: center;
    font-weight: bold;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.5);
}

.subjectcode {
    position: absolute;
    top: 50px;
    left: 525px; 
    background-color: rgb(255, 255, 255);
    font-family: 'K2D', sans-serif;
    border-radius: 20px;
    width: 303px;
    height: 58px;
    text-align: center; 
    display: flex;
    justify-content: center;
    align-items: center;
    font-weight: bold;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.5);
}
#submit {
    position: absolute;
    top: 50px;
    left: 1000px; 
    background-color: rgb(255, 255, 255);
    font-family: 'K2D', sans-serif;
    border-radius: 20px;
    width: 303px;
    height: 58px;
    text-align: center; 
    display: flex;
    justify-content: center;
    align-items: center;
    font-weight: bold;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.5);
    border: 0px;
    background-color: red;
}
.questionbar {
    position: absolute;
    top: 170px;
    left: 10vh;
    background-color: rgb(255, 255, 255);
    font-family: 'K2D', sans-serif;
    border-radius: 20px;
    width: 750px;
    height: 58px;
    text-align: center; 
    display: flex;
    justify-content: center;
    align-items: center;
    font-weight: bold;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.5);
}
.navbar{
    position: absolute;
    top: 0;
    left: 0;
    background-color: rgb(255, 255, 255);
    font-family: 'K2D', sans-serif;
    border-radius: 20px;
    width: 125px;
    height: 58px;
    text-align: center; 
    display: flex;
    justify-content: center;
    align-items: center;
    font-weight: bold;
    
}
#q1{
    left: 17%;
    border: 0px;
    
}
#plus{
    left: 33.9%;
    border: 0px;
}
#inputbox{
    background-color: #ffffff;
    height: 600px;
    top: 36vh;
    text-align: left;
    border: 0px;
    
}
#qnum {
    position: absolute;
    width: 330px;
    bottom: 0;
    top: 40vh;
    left: 290px;
    background-color: rgb(255, 255, 255);
    font-weight: 900;
    font-size: 25px;
    white-space: nowrap;

}
#outputbox {
    background-color: #ffffff;
    height: 600px;
    width: 330px;
    top: 36vh;
    text-align: left;
    border: 0px;
    left: 980px; 
}
#qoutput{
    position: absolute;
    width: 250px;
    bottom: 0;
    top: 40vh;
    left: 1025px;
    background-color: rgb(255, 255, 255);
    font-weight: 900;
    font-size: 25px;
    white-space: nowrap;

}
#mm{
    left: 1100px;
}




</style>



<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="Question.css">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=K2D:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800&display=swap" rel="stylesheet">
<title>Background Image Example</title>
</head>
<body>
<div class="MainBox">
    <div class="Runs">Max Runs</div>
    <div class="subjectcode">UES103</div>
    <button id="submit">Submit</button>
    <div class="questionbar">
        <div class="navbar">Question</div>
        <button class="navbar" id="q1">Q1</button>
        <button class="navbar" id="plus">+</button>
        <div class="navbar" id="mm">MM - </div>
    </div>
   
    <input type="text" placeholder="Enter question" class="questionbar" id="inputbox">
    <div class="questionbar" id="qnum">Question Number 1</div>
    <input type="text" placeholder="Enter output" class="questionbar" id="outputbox">
    <div class="questionbar" id="qoutput"> Output</div>
    














</div>
</body>
</html>

editor/teacher/templates/teacher/SubjectInfo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="SubjectCss.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=K2D:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800&display=swap" rel="stylesheet">
</head> 
<body>
    <div id="MainBox">
        <p id="Heading">SubjectCode</p>
        <hr>
        <div class="info1">Maximum Marks
            <div id="Box1">30</div>
        </div>
        <div class="info2">Test date and time
            <div id="Box2">30</div>
        </div>
        <div class="info3">Duration
            <div id="Box3">30</div>
        </div>
        <div class="info4">Submitted by
            <div id="Box4">30</div>
        </div>
        <div class="info5">
            <div id="Box5">30</div>
        </div>
        <div class="info6">
            <button id="Box6">Evaluate</button>
        </div>






    </div>
</body>
</html>

editor/teacher/templates/teacher/TeacherLoginPage.html
{% extends 'base.html' %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="styles1.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=K2D:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800&display=swap" rel="stylesheet">
</head>
<body>
    <div class="container">
      
            <h1>Welcome User</h1>

            <p>Created tests</p>
            <hr class="customLine">
            <div class="TestInfo">
                SubjectCode
                <div class="status">
                    <button id="checkstatus">Check Status</button>
                </div>

            </div>

            <button id="createTest">Create Test</button>
        
    </div>
</body>

editor/teacher/templates/teacher/add_questions.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<style>
body {
  background-image: url("https://c4.wallpaperflare.com/wallpaper/285/172/9/sunset-8k-forest-4k-wallpaper-preview.jpg");
  background-size: cover;
  background-repeat: no-repeat;
  background-attachment: fixed;
  display: flex;
  justify-content: center;
  align-items: center;
  height: 100vh;
  margin: 0;
}

.MainBox {
  background-color: rgba(255, 255, 255, 0.9);
  width: 90%;
  max-width: 90vw;
  height: 80vh;
  border-radius: 20px;
  display: flex;
  flex-direction: row; /* Make items horizontal */
  flex-wrap: wrap; /* Wrap items to next line if needed */
  justify-content: center;
  align-items: center;
  position: relative;
  backdrop-filter: blur(300px);
}

.Runs, .subjectcode, #submit, .questionbar, .navbar {
  background-color: rgb(255, 255, 255);
  font-family: 'K2D', sans-serif;
  border-radius: 20px;
  width: 30%;
  max-width: 30vw;
  height: 10%;
  max-height: 10vh;
  text-align: center;
  display: flex;
  justify-content: center;
  align-items: center;
  font-weight: bold;
  box-shadow: 0 0 10px rgba(0, 0, 0, 0.5);
  margin: 10px; /* Add spacing between items */
}

#submit {
  background-color: red;
}

#inputbox, #outputbox {
  background-color: #ffffff;
  height: 50%;
  max-height: 50vh;
  width: 50%;
  max-width: 50vw;
  text-align: left;
}

#qnum, #qoutput {
  background-color: rgb(255, 255, 255);
  font-weight: 900;
  font-size: 2em;
  white-space: nowrap;
}

#qnum, #qoutput, .navbar {
  width: auto;
  height: auto;
}

</style>
<!-- <div class="MainBox">
  <div class="Runs">Max Runs</div>
  <div class="subjectcode">UES103</div>
  <button id="submit">Submit</button>
  <div class="questionbar">
      <div class="navbar">Question</div>
      <button class="navbar" id="q1">Q1</button>
      <button class="navbar" id="q1">Q1</button>
      
      <button class="navbar" id="plus">+</button>
  </div>
  <div class="navbar" id="mm">MM - </div>

 
  <input type="text" placeholder="Enter question" class="questionbar" id="inputbox">
  <div class="questionbar" id="qnum">Question Number 1</div>
  <input type="text" placeholder="Enter output" class="questionbar" id="outputbox">
  <div class="questionbar" id="qoutput"> Output</div>


</div> -->

<div style="display: flex; flex-direction: row; gap: 10px;">
  <!-- Loop through all questions -->
  {% if all_questions %}
      {% for question in all_questions %}
          <form method="get" action="{% url 'add_question' test_id=question.test.id q_id=question.id %}">
              <button type="submit" class="btn btn-primary">Question {{ forloop.counter }}</button>
          </form>
      {% endfor %}
  {% endif %}
</div>
<h2>Add Question</h2>
<form method="post" action="{% url 'add_question' test_id=test.id q_id=question.id %}">
  {% csrf_token %}
  <input type="hidden" name="question_id" value="{{ question.id }}">
  <div class="form-group">
    <textarea name="question_text" class="form-control" id="exampleFormControlTextarea1" rows="3">{{ question.question_text }}</textarea>
  </div>
  <button type="submit" class="btn btn-primary">Save Question</button>
</form>
<form method="post" action="{% url 'new_question' test_id=test.id%}">
  {% csrf_token %}
  <input type="hidden" name="new_question">
  <button type="submit" class="btn btn-primary">Add New Question</button>
</form>

{% endblock content %}

editor/teacher/templates/teacher/add_test.html
{% extends 'base.html' %} 
{% block content %}
<h2>Create Test</h2>
<button type="button" class="btn btn-primary" id="createTestBtn">Create Test</button>

<div class="modal fade" id="createTestModal" tabindex="-1" role="dialog" aria-labelledby="createTestModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="createTestModalLabel">Create Test</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form method="post" action="{% url 'teacher:create_test' %}">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>

<!-- Include jQuery and Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

<script>
    $(document).ready(function(){
        $("#createTestBtn").click(function(){
            $("#createTestModal").modal('show');
        });
    });
</script>
{% endblock content %}
    

editor/teacher/templates/teacher/create_questions.html
{% extends "base.html" %}
{% block content %}
    <h1>Home</h1>
    <p>Welcome to the home page!</p>
{% endblock %}

editor/teacher/templates/teacher/dashboard.html
{% extends 'base.html' %} 
{% block content %} 
{% if messages %}
<ul class="messages">
  {% for message in messages %}
  <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>
    {{ message }}
  </li>
  {% endfor %}
</ul>
{% endif %} 
<div class="d-flex justify-content-end w-100">
</div>
<div class="card mt-5 mb-5" style="border-radius: 25px; color:black">
  <div class="card-body">
    <div class="container">
        <h2>Created Tests</h2>
      <div class="row">
        <div class="col-md-6"> <!-- Adjust this value to your needs -->
            {% for test in tests %}
            <li class="list-group-item d-flex align-items-center" id="" style="background-color: black;">
              <div class="p-2 flex-grow-1">
                <h5 style="color:white">{{ test.subject_Code }}</h5>
              </div>
          
              
            {% endfor %}
            
            <div class="row">
              <div class="col-12 d-flex justify-content-center">
                  <form action="{%url 'teacher:create_test'%}" method="post">
                      {% csrf_token %}
                      <button type="submit" class="btn btn-primary">Create Test</button>
                  </form>
              </div>
            </div>
          </div>
  </div>
</div>
{% endblock content %}