editor/authentication/urls.py
from django.urls import path
from . import views

app_name = 'authentication'

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('register/', views.register, name='register'),
    path('about/', views.about, name='about'),
    path('instructions/', views.instructions, name='instructions'),


]

editor/editor/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
    path('student/', include('student.urls')),
    path('teacher/', include('teacher.urls')),
    path('makeTest/', include('makeTest.urls')),
]

editor/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}{% endblock title%}</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=K2D:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="SubjectCss.css">
    
  {% block head %}{% endblock head %}
    
  {% load static %}
  <style>
    body {
      background-image: url('https://c4.wallpaperflare.com/wallpaper/285/172/9/sunset-8k-forest-4k-wallpaper-preview.jpg');
      background-size: cover;
    }
    
    .navtext{
      font-family: "Inter", sans-serif !important; 
      font-weight: 300;
      font-size: 24px;
    }
    .box1 {
      background-color: rgba(255, 255, 255, 0.7); 
      color: #fff;
      backdrop-filter: blur(50px); 
      box-shadow: 0 0 10px rgba(0, 0, 0, 0.5); 
    }
    .box2 {
      background-color: #ffffff;
      color: #fff;
      opacity: 1; 
      box-shadow: 0 0 10px rgba(0, 0, 0, 0.5); 
    }
    
    .navbar-nav .nav-link {
      color: #000 !important; 
      font-family: "Inter", sans-serif !important; 
      font-weight: 300; 
        }
      button {
      border: none;
      outline: none;
      background-color: #ffffff;
      color: #000; 
      padding: 15px 32px; 
      text-align: center; 
      text-decoration: none;
      display: inline-block; 
      font-size: 16px; 
      cursor: pointer; 
      border-radius: 8px; 
    }
    


    button:hover {
      background-color: #f0f0f0; 
    }
    .navelements
      {
      display: flex;
      align-items: center; 
      justify-content: center;
    }
    .healthicons--i-exam-multiple-choice-outline {
  display: inline-block;
  width: 1em;
  height: 1em;
  --svg: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 48 48'%3E%3Cg fill='%23000'%3E%3Cpath d='M20 15a1 1 0 0 1 1-1h8a1 1 0 1 1 0 2h-8a1 1 0 0 1-1-1m1 3a1 1 0 1 0 0 2h8a1 1 0 1 0 0-2zm-1 10a1 1 0 0 1 1-1h8a1 1 0 1 1 0 2h-8a1 1 0 0 1-1-1m1 3a1 1 0 1 0 0 2h8a1 1 0 1 0 0-2z'/%3E%3Cpath fill-rule='evenodd' d='M10 27a1 1 0 0 1 1-1h5a1 1 0 0 1 1 1v5a1 1 0 0 1-1 1h-5a1 1 0 0 1-1-1zm2 1v3h3v-3z' clip-rule='evenodd'/%3E%3Cpath d='M17.707 15.707a1 1 0 0 0-1.414-1.414L13 17.586l-1.293-1.293a1 1 0 0 0-1.414 1.414L13 20.414z'/%3E%3Cpath fill-rule='evenodd' d='M10 6a4 4 0 0 0-4 4v28a4 4 0 0 0 4 4h20a4 4 0 0 0 4-4V10a4 4 0 0 0-4-4zm-2 4a2 2 0 0 1 2-2h20a2 2 0 0 1 2 2v28a2 2 0 0 1-2 2H10a2 2 0 0 1-2-2zm28 6a3 3 0 1 1 6 0v20.303l-3 4.5l-3-4.5zm3-1a1 1 0 0 0-1 1v2h2v-2a1 1 0 0 0-1-1m0 22.197l-1-1.5V20h2v15.697z' clip-rule='evenodd'/%3E%3C/g%3E%3C/svg%3E");
  background-color: currentColor;
  -webkit-mask-image: var(--svg);
  mask-image: var(--svg);
  -webkit-mask-repeat: no-repeat;
  mask-repeat: no-repeat;
  -webkit-mask-size: 100% 100%;
  mask-size: 100% 100%;
}

  </style>
  
</head>
<body>
  {% load static %}
  <div class="wrapper" >
    <div style="width: 1326px; height: 750px; position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%); border-radius: 48px; " class="box box1">
      
      {% block navbar %}
        
      {% endblock navbar %}
        
      <div style="width: 1171px; margin: 0 auto;">
          {% block content%} {% endblock content %}
      </div>
  </div>
  {% block modal%} {% endblock modal %}
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

</body>
</html>

editor/templates/navbar.html
{% extends 'base.html' %}

{% block navbar %}
<nav style="width: 1171px; height: 86px;border-radius: 30px; background-color: #ffffff; opacity: 1;margin:0 auto;margin-top: 33px;" class="navbar navbar-expand-lg navbar-light bg-light box2">
    <div class="container dark-white-bg rounded p-3">
    <div class="navbar-brand" style="font-family: 'Inter', sans-serif !important; font-weight: bold; font-size: 34px;padding-left: 20px; " >ExamIn</div>
    
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ms-auto">   
          <div class="navtext">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'authentication:login' %}" style="margin-left: auto;">Home</a>
            </li>
          </div>
        <div class="navtext">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'authentication:about' %}" style="margin-left: auto;">About</a>
          </li>
        </div>
        <div class="navtext">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'authentication:instructions' %}" style="margin-left: auto;">Instructions</a>
          </li>
        </div>
        <div class="navtext">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'authentication:register' %}" style="margin-left: auto;">SignUp</a>
          </li>
        </div>
        <div class="navtext">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'authentication:logout' %}" style="margin-left: auto;">Logout</a>
          </li>
        </div>
        
        </ul>
      </div>
    </div>
  </nav>
  
  {% block content_nav %}
    
  {% endblock content_nav %}
    
{% endblock navbar %}
    