editor/editor/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
    path('student/', include('student.urls')),
    path('teacher/', include('teacher.urls')),
    path('makeTest/', include('makeTest.urls')),
]

editor/makeTest/urls.py
from django.urls import path
from . import views
app_name = "makeTest"

urlpatterns = [
    path('', views.create_test, name='create_test'),
    path('test/<int:test_id>/question/<int:q_id>', views.add_question, name='add_question'),
    path('makeTest/test/<int:test_id>/question/', views.view_question, name='view_question'),
    path('test/<int:test_id>/new_question/', views.new_question, name='new_question'),
    path('test/<int:test_id>/delete_test/', views.delete_test, name='delete_test'),
    path('test/<int:test_id>/delete_question/<int:q_id>', views.delete_question, name='delete_question'),
    path('test/<int:test_id>/publish/', views.publish, name='publish'),

]

editor/makeTest/models.py
# models.py
from django.db import models
from django.utils import timezone

class Test(models.Model):
    name = models.CharField(max_length=200)
    subject = models.CharField(max_length=200)
    datecreated = models.DateTimeField(default=timezone.now)
    total_marks = models.IntegerField()
    exam_code = models.CharField(max_length=200, default='123AB')
    published_bool = models.BooleanField(default=False)
    def __str__(self):
        return self.name
    
class PublishedTest(models.Model):
    name = models.CharField(max_length=200)
    subject = models.CharField(max_length=200)
    datecreated = models.DateTimeField(default=timezone.now)
    total_marks = models.IntegerField()
    exam_code = models.CharField(max_length=200, default='123AB')
    published_bool = models.BooleanField(default=False)

    def __str__(self):
        return self.exam_code

class Question(models.Model):
    test = models.ForeignKey(Test, on_delete=models.CASCADE)
    max_marks = models.IntegerField(default=1)
    question_text = models.CharField(max_length=2000)
    answer_text = models.TextField(null=True, default='')
    

    def __str__(self):
        return self.question_text

editor/makeTest/forms.py
# forms.py
from django import forms
from .models import Test

class TestForm(forms.ModelForm):
    class Meta:
        model = Test
        fields = ['name', 'subject', 'total_marks']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'subject': forms.TextInput(attrs={'class': 'form-control'}),
            'total_marks': forms.NumberInput(attrs={'class': 'form-control'}),
        }

editor/makeTest/views.py
# views.py
from django.shortcuts import render, redirect, get_object_or_404,HttpResponse
from .forms import TestForm
from .models import Test, Question,PublishedTest
import string, random

def generate_unique_exam_code():
    while True:
        code = ''.join(random.choices(string.ascii_uppercase + string.digits, k=6))  # Generate a random string of 6 uppercase letters and digits
        if not Test.objects.filter(exam_code=code).exists():  # Check if the code is unique
            return code
        

def create_test(request):
    if request.method == 'POST':
        form = TestForm(request.POST)
        if form.is_valid():
            test = form.save(commit=False)
            test.exam_code = generate_unique_exam_code()
            test.save()
            question = Question.objects.create(test=test, question_text="", max_marks=1)
            return redirect('makeTest:add_question', test_id=test.pk, q_id=question.pk)
    else:
        form = TestForm()
    tests = Test.objects.all()
    return render(request, 'createtest/create_test.html', {'form': form, 'tests': tests})

def add_question(request, test_id, q_id=None):
    test = get_object_or_404(Test, pk=test_id)
    if request.method == 'POST':
        question_text = request.POST.get('question_text')
        max_marks = request.POST.get('max_marks')
        if question_text and max_marks and q_id is not None:
            current_question = get_object_or_404(Question, pk=q_id)
            current_question.question_text = question_text
            current_question.max_marks = max_marks
            current_question.save()
        return redirect('makeTest:add_question', test_id=test.pk, q_id=q_id)
    else:
        if q_id is None:
            current_question = Question.objects.create(test=test, question_text="", max_marks=1)
        else:
            current_question = get_object_or_404(Question, pk=q_id)
        all_questions = Question.objects.filter(test=test)
        return render(request, 'createtest/add_question.html', {'test': test, 'question': current_question, 'all_questions': all_questions, 'current_question': current_question})

def view_question(request, test_id):
    test = get_object_or_404(Test, pk=test_id)
    question = Question.objects.filter(test=test).first()  # Get the first question of the test
    all_questions = Question.objects.filter(test=test)
    return render(request, 'createtest/add_question.html', {'test': test, 'question': question, 'all_questions': all_questions})

def new_question(request, test_id):
    test = get_object_or_404(Test, pk=test_id)
    new_question = Question.objects.create(test=test, question_text="", max_marks=1)
    return redirect('makeTest:add_question', test_id=test.pk, q_id=new_question.pk)

def delete_test(request, test_id):
    if request.method == 'POST':
        test = get_object_or_404(Test, pk=test_id)
        test.question_set.all().delete()  # Delete all questions related to the test
        print(test.question_set.all())
        test.delete()
    return redirect('makeTest:create_test')

def publish(request, test_id):
    if request.method == 'GET':
        # Retrieve the Test object with the given test_id or return a 404 error if not found
        test_to_copy = get_object_or_404(Test, pk=test_id)
        
        # Create a new PublishedTest object and copy the necessary fields from the Test object
        published_test = PublishedTest(
            name=test_to_copy.name,
            subject=test_to_copy.subject,
            datecreated=test_to_copy.datecreated,
            total_marks=test_to_copy.total_marks,
            exam_code=test_to_copy.exam_code,
            published_bool=True  # Set published_bool to True for the PublishedTest
        )
        
        # Save the new PublishedTest object
        published_test.save()
        
        # Update the published_bool field of the Test object
        test_to_copy.published_bool = True
        test_to_copy.save()
        
        # Redirect to the specified URL
        return redirect('makeTest:create_test')
    else:
        # Handle the case where the request method is not POST
        return HttpResponse("Only POST requests are allowed for this view")
   


def delete_question(request, test_id, q_id):
    if request.method == 'POST':
        question = get_object_or_404(Question, pk=q_id)
        test = get_object_or_404(Test, pk=test_id)
        question.delete()
        # Get the previous question
        previous_question = Question.objects.filter(test_id=test_id, id__lt=q_id).order_by('-id').first()
        if previous_question is not None:
            return redirect('makeTest:add_question', test_id=test_id, q_id=previous_question.id)
        else:
            # If there is no previous question, get the next question
            next_question = Question.objects.filter(test_id=test_id, id__gt=q_id).order_by('id').first()
            if next_question is not None:
                return redirect('makeTest:add_question', test_id=test_id, q_id=next_question.id)
            else:
                # If there is no next question, redirect to the test
                test.delete()
                return redirect('makeTest:create_test')

editor/makeTest/templates/createtest/add_question.html
<!-- add_question.html -->
{% extends 'base.html' %}
{% block content %}
<div style="display: flex; flex-direction: row; gap: 10px;">
    <!-- Loop through all questions -->
    {% if all_questions %}
        {% for question in all_questions %}
            <form method="get" action="{% url 'makeTest:add_question' test_id=question.test.id q_id=question.id %}">
                <button type="submit" class="btn {% if question.id == current_question.id %}btn-success{% else %}btn-primary{% endif %}">Question {{ forloop.counter }}</button>
            </form>
        {% endfor %}
    {% endif %}
</div>
<h2>Add Question</h2>
<form method="post" action="{% url 'makeTest:add_question' test_id=test.id q_id=question.id %}">
    {% csrf_token %}
    <input type="hidden" name="question_id" value="{{ question.id }}">
    <div class="form-group">
      <textarea name="question_text" class="form-control" id="exampleFormControlTextarea1" rows="3">{{ question.question_text }}</textarea>
    </div>
    <div class="form-group">
        <label for="maxMarks">Maximum Marks</label>
        <input type="number" class="form-control" id="maxMarks" name="max_marks" value="{{ question.max_marks }}">
    </div>
    <button type="submit" class="btn btn-primary">Save Question</button>
</form>
<form method="post" action="{% url 'makeTest:new_question' test_id=test.id%}">
    {% csrf_token %}
    <input type="hidden" name="new_question">
    <button type="submit" class="btn btn-primary">Add New Question</button>
</form>

<form method="post" action="{% url 'makeTest:create_test'%}">
    {% csrf_token %}
    <button type="submit" class="btn btn-primary">Finish Adding Questions</button>
</form>

<form method="post" action="{% url 'makeTest:delete_question' test_id=question.test.id q_id=question.id %}">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Delete question</button>
</form>
{% endblock %}

editor/makeTest/templates/createtest/create_test.html
{% extends 'navbar.html' %}

{% block content_nav %}
<div class="container" style="margin: 50px;">
    <h2>Create Test</h2>
    <button type="button" class="btn btn-primary" id="createTestBtn">Create Test</button>

    <style>
        .card-container {
            max-height: 400px;
            max-width: 1200px;
            overflow-y: auto;
        }
    </style>

    <div class="row card-container" style = "color: black;">
        {% for test in tests %}
            <div class="col-sm-4">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">{{ test.name }}</h5>
                        <p class="card-text">Subject: {{ test.subject }}</p>
                        <p class="card-text">Total Marks: {{ test.total_marks }}</p>
                        <p class="card-text">Exam Code: {{ test.exam_code }}</p> 
                        <a href="{% url 'makeTest:view_question' test_id=test.id%}" class="btn btn-primary">Go to Test</a>
                        <form method="post" action="{% url 'makeTest:delete_test' test_id=test.id %}">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger">Delete Test</button>
                        </form>
                        {% if test.published_bool %}
                            <h1>Published</h1>
                        {% else %}
                            <!-- <form method="post" action="{% url 'makeTest:publish' test_id=test.id %}"> -->
                            <form method="post" action="#"></form>
                                {% csrf_token %}
                                <button type="submit" class="btn btn-success">Publish</button>
                            </form>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

{% block modal %}
<div class="modal fade" id="createTestModal" tabindex="-1" role="dialog" aria-labelledby="createTestModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document" style = "z-index: 1050;">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="createTestModalLabel">Create Test</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form method="post" action="{% url 'makeTest:create_test' %}">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>

<script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-beta1/js/bootstrap.bundle.min.js"></script>
<script>
    document.getElementById('createTestBtn').addEventListener('click', function() {
        var myModal = new bootstrap.Modal(document.getElementById('createTestModal'), {});
        myModal.show();
    });
</script>
{% endblock %}